name: CobaltCore
main: org.jacob.spigot.plugins.CobaltCore.Main
version: 1.0
api-version: "1.13"
commands:
  discord:
  cobaltcore:
  announce:
  sc:
  forceannounce:
  blacklist:
  launch:
  punish:
  ranks:
  spawnershop:
  nether:
  world: